---
- name: enable firewall service
  hosts: all
  become: yes
  tasks:
   - name: ensure firewalld is installed
     package:     #module
       name: firewalld     #service name
       state: present      

   - name: enable firewalld
     firewalld:        #service 
      #service: nginx
      port: 80/tcp
      permanent: true
      state: enabled

   - name: reload firewalld
     service:      #module
      name: firewalld
      state: reloaded    
...

