---
- name: enable firewall service
  hosts: all
  tasks:
   - name: enable firewalld
     firewalld:
      service: nginx
      permanent: true
      state: enabled

   - name: reload firewalld
     service: 
      name: firewalld
      state: enabled
...

