---
- name: Test Playbook
  hosts: all
  become: yes
  tasks:
    #- name: stop nginx
     # service:
      # name: nginx
       #state: stopped
       #enabled: no

    #- name: Remove nginx
     # apt:
      #  name: nginx
       # state: absent

    - name: update catche
      apt:
       update_cache: yes
    - name: install nginx
      apt:
       name: nginx
       state: present
    - name: ensure service started
      service:
       name: nginx
       state: started
       enabled: yes

    - name: create file
      file:
       state: 
...