---
- name: Test Playbook
  hosts: all
  become: yes
  tasks:
    - name: stop nginx
      service:
      name: nginx
      
    - name: Remove nginx
      apt:
        name: nginx
        state: absent
...
