---
- name: modules practice playbook
  hosts: all
  become: yes #command to run task with root prevelleges
  tasks:
    - name: print msg
      debug:
        msg: "hello world"
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: install httpd
      apt:
        name: httpd
        state: present      
...