---
- name: modules practice playbook
  hosts: all
  become: yes                                            #command to run task with root prevelleges
  tasks:
    #- name: print msg                                   #script to pring msg msg
      #debug:
        #msg: "hello world"
    - name: Update apt package cache                    # script to apt update  
      apt:
        update_cache: yes
    - name: install nginx                            # script to install packages
      apt:
        name: nginx
        state: present
    - name: ensure nginx started & enabled           #script to start & enable service
      service:
        name: nginx 
        state: started  
        enabled: yes
    #- name: stop apache2                               #Script to stop service
      #service:
       #name: apache2
       #state: stopped
       #enabled: no
    #- name: restart apache2                           #Script to restart service
      #service:
       #name: apache2
       #state: restarted
       #enabled: yes
    #- name: remove apache2                            #script to remove service
      #apt:
       #name: apache2
       #state: absent 

           
...