---
- name: modules practice playbook
  hosts: all
  tasks:
    - name: print msg
      debug:
        msg: "hello world"
    - name: install nginx
      apt:
        name: nginx
        state: present      
...