---
- name: modules practice playbook
  hosts: all
  become: yes #command to run task with root prevalages
  tasks:
    - name: print msg
      debug:
        msg: "hello world"
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: absent      
...