---
- name: modules practice playbook
  hosts: all
  tasks:
    - name: print msg
      debug:
        msg: "hello world"
    - name: install package
      apt-get:
        name: nginx
        state: present      
...