---
- name: my second playbook
  hosts: all
  become: yes
  tasks:
    - name: my first task
      debug:
        msg: "hello everyone"
      tags: first tag
    - name: my second task
      debug:
        msg: "good morning"
      tags: second tag 
    - name: bharti's hobbies list
      debug:
        msg:
          - paining
          - coocking
          - music
          - and the most fevorite is sleeping 
      tags: third tag    

    - name: bharti's diet plan
      debug:
        msg: 
          - tea & breckfast at 9:0 am
          - take fruits at 11:0 am
          - lunch arount 1:30 pm
          - tea around 5:00 pm
          - dinner arount 9:30 pm
      tags: four tag
    - name: my address details
      debug:
        msg: 
          city: ch. Sambhaji Nagar
          state: Maharashtra
          Country: India
      tags: five tag
    - name: msg for you
      debug:
        msg: |
          heyyyy
          good morning
          how are you doing?????? 
      tags: six tag
    - name: second msg
      debug:
        msg: |  
          hello,i am doing well
      tags: seven tag            
...
