---
- name: user creation & management
  hosts: all
  become: yes
  tasks:
   - name: create user & add into group & delete
     user:
      name: chetan
      comment: creating chetan user
      #home: <path>                    #default home dir is /home/chetan , add path if want to give specifc home dir
      shell: /bin/bash                #default shell   
      #group: evc                       #add in single group
      #groups: anant, tata              #add in multiple group 
      #state: absent                     #delete user 
      #remove: yes                       # delete all user data like home directory 
...
