---
#- name: nginx installation 
  #hosts: all
  #become: yes
  #tasks:
   - name: installing nginx
     package:
      name: nginx
      state: present
    
   - name: customizing index.html page 
     copy:
      src: index.html
      dest: /var/www/html/
     notify: 
        - starting nginx

   - name: print msg
     debug:
      msg: "{{URL}}"

...      
