---

 
   - name: installing nginx
     package:
      name: nginx
      state: present
    
   - name: customizing index.html page 
     copy:
      src: index.html
      dest: /var/www/html/index.html
     notify: 
        - starting & enable nginx

   - name: print msg
     debug:
      msg: "{{URL}}"

...      
